exams:
  cpa-10: 
    test_numbers: ["01", "02", "03", "04", "05", "06", "07", "08"]
    total_number_questions: 50
    chunk_size: 10
    passing_threshold: 0.7

  ancord-aai:
    test_numbers: ["01", "02", "03", "04", "05", "06"]
    total_number_questions: 80
    chunk_size: 20
    passing_threshold: 0.7

model_names:
  - gemini-2.5-flash-lite
  - gemini-2.5-flash
  - gpt-5-nano
  - deepseek-r1-distill-qwen-14B
  - deepseek-r1-distill-llama-8B
  - gemma-3-27B-it
  - gpt-oss-20B
  - llama-3.1-8B-instruct
  - llama-3.3-70B-instruct
  - qwen3-4B-instruct

models:
  gemini: 
    - gemini-2.5-flash-lite
    - gemini-2.5-flash
  gpt-5: 
    - gpt-5-nano
  hugging_face:
    deepseek-r1-distill-qwen-14B: 
      model_repo: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
      provider: novita
      max_tokens: 4096
    deepseek-r1-distill-llama-8B:
      model_repo: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
      provider: nscale
      max_tokens: 8192
    gemma-3-27B-it:
      model_repo: google/gemma-3-27b-it
      provider: nebius
      max_tokens: 4096
    gpt-oss-20B:
      model_repo: openai/gpt-oss-20b
      provider: together
      max_tokens: 16384
    llama-3.1-8B-instruct:
      model_repo: meta-llama/Llama-3.1-8B-Instruct
      provider: cerebras
      max_tokens: 4096
    llama-3.3-70B-instruct:
      model_repo: meta-llama/Llama-3.3-70B-Instruct
      provider: cerebras
      max_tokens: 4096
    qwen3-4B-instruct:  
      model_repo: Qwen/Qwen3-4B-Instruct-2507
      provider: nscale
      max_tokens: 4096

ignored_questions:
  cpa-10: 
    "01": ["24", "25", "41"]
    "02": ["28", "39", "41"]
    "03": []
    "04": []
    "05": ["30", "34"]
    "06": ["31"]
    "07": []
    "08": ["24", "25"]
  
  ancord-aai: 
    "01": ["43"]
    "02": []
    "03": ["39"]
    "04": ["43", "47", "49", "67"]
    "05": ["78"]
    "06": ["78"]
  
material_topics:
  cpa-10:
    1: "Sistema Financeiro Nacional e Participantes do Mercado"
    2: "Compliance Legal, Ética e API"
    3: "Princípios Básicos de Economia e Finanças"
    4: "Instrumentos de Renda Fixa, Renda Variável e Derivativos"
    5: "Fundos de Investimentos"
    6: "Produtos de Previdência Complementar"
    7: "Mensuração e Gestão de Performance"