exams:
  cpa-10: 
    test_numbers: [
      "01",
      "02",
      "03",
      "04",
      "05",
      "06",
      "07",
      "08"
    ]
    total_number_questions: 50
    chunk_size: 10

  ancord-aai:
    test_numbers: [
      "01",
      "02",
      "03",
      "04",
      "05",
      "06"
    ]
    total_number_questions: 80
    chunk_size: 20

model_names:
  - gemini-2.5-flash-lite
  - gemini-2.5-flash
  - gpt-5-nano
  - deepseek-r1-distill-qwen-14B
  - deepseek-r1-distill-llama-8B
  - gemma-3-27B-it
  - gpt-oss-20B
  - llama-3.1-8B-instruct
  - llama-3.3-70B-instruct
  - qwen3-4B-instruct

models:

  gemini: 
    - gemini-2.5-flash-lite
    - gemini-2.5-flash

  gpt-5: 
    - gpt-5-nano
  
  hugging_face:
    deepseek-r1-distill-qwen-14B: 
      provider: novita
      max_tokens: 4096
    deepseek-r1-distill-llama-8B:
      provider: nscale
      max_tokens: 8192
    gemma-3-27B-it:
      provider: nebius
      max_tokens: 4096
    gpt-oss-20B:
      provider: together
      max_tokens: 16384
    llama-3.1-8B-instruct:
      provider: cerebras
      max_tokens: 4096
    llama-3.3-70B-instruct:
      provider: cerebras
      max_tokens: 4096
    qwen3-4B-instruct:
      provider: nscale
      max_tokens: 4096

ignored_questions:
  cpa-10: 
    "01": ["24", "25", "41"]
    "02": ["28", "39", "41"]
    "03": []
    "04": []
    "05": ["30", "34"]
    "06": ["31"]
    "07": []
    "08": ["24", "25"]
  
  ancord-aai: 
    "01": ["43"]
    "02": []
    "03": ["39"]
    "04": ["43", "47", "49", "67"]
    "05": ["78"]
    "06": ["78"]
  